//project "Algs4"
#r "Accessibility"
#r "FSharp.Core, Version=4.3.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a"
#r "FSharp.Data.TypeProviders, Version=4.3.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a"
#r "PresentationCore"
#r "PresentationFramework"
#r "PresentationUI"
#r "System"
#r "System.Configuration"
#r "System.Core"
#r "System.Data"
#r "System.Drawing"
#r "System.Numerics"
#r "System.Xaml"
#r "System.Xml"
#r "UIAutomationProvider"
#r "UIAutomationTypes"
#r "WindowsBase"
#r "mscorlib"
#r @".\packages\FSharpx.TypeProviders.1.5.3\Lib\FSharpx.Core.dll"
#r @".\packages\FSharpx.TypeProviders.1.5.3\Lib\FSharpx.TypeProviders.dll"
#load @".\Algs4\Algs4\App.fs"
