//project "Algs4"
#r "Accessibility"
#r "FSharp.Core, Version=4.3.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a"
#r "FSharp.Data.TypeProviders, Version=4.3.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a"
#r "FSharp.PowerPack, Version=2.0.0.0, Culture=neutral, PublicKeyToken=a19089b1c74d0809"
#r "FSharp.PowerPack.Linq, Version=2.0.0.0, Culture=neutral, PublicKeyToken=a19089b1c74d0809"
#r "FSharp.PowerPack.Metadata, Version=2.0.0.0, Culture=neutral, PublicKeyToken=a19089b1c74d0809"
#r "FSharp.PowerPack.Parallel.Seq, Version=2.0.0.0, Culture=neutral, PublicKeyToken=a19089b1c74d0809"
#r "PresentationCore"
#r "PresentationFramework"
#r "PresentationUI"
#r "System"
#r "System.Configuration"
#r "System.Core"
#r "System.Data"
#r "System.Drawing"
#r "System.Numerics"
#r "System.Xaml"
#r "System.Xml"
#r "UIAutomationProvider"
#r "UIAutomationTypes"
#r "WindowsBase"
#r "mscorlib"
#r @".\packages\FSharpx.TypeProviders.1.5.3\Lib\FSharpx.Core.dll"
#r @".\packages\FSharpx.TypeProviders.1.5.3\Lib\FSharpx.TypeProviders.dll"
#r @".\packages\Unquote.2.2.2\lib\net40\Unquote.dll"
#r @".\packages\xunit.1.9.1\lib\net20\xunit.dll"
#load @".\Algs4\Algs4\App.fs"
#load @".\Algs4\Algs4\UnionStructure.fs"
#load @".\Algs4\Algs4\tests.fs"
